#!/bin/bash
# YADM Bootstrap Script
# Automatically generated by setup-yadm-master-config.sh

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}=== YADM Configuration Bootstrap ===${NC}"
echo -e "${YELLOW}Bootstrapping master configuration...${NC}"

# Clone or update yadm repository
if [ -d "$HOME/.local/share/yadm/repo.git" ]; then
    echo -e "${GREEN}✓ YADM repository exists${NC}"
    cd "$HOME"
    yadm pull || echo -e "${YELLOW}Warning: Could not pull latest changes${NC}"
else
    echo -e "${RED}✗ YADM repository not found${NC}"
    echo "Please run setup-yadm-master-config.sh first"
    exit 1
fi

# Create necessary directories
mkdir -p "$HOME/.local/bin"
mkdir -p "$HOME/.local/share"
mkdir -p "$HOME/tmp"

# Set up permissions
chmod 700 "$HOME/.ssh" 2>/dev/null || true
chmod 700 "$HOME/.gnupg" 2>/dev/null || true

# Source shell configurations
echo -e "${YELLOW}Sourcing shell configurations...${NC}"
[ -f "$HOME/.zshenv" ] && source "$HOME/.zshenv"
[ -f "$HOME/.zshrc" ] && source "$HOME/.zshrc"

echo -e "${GREEN}✓ Bootstrap completed successfully!${NC}"
echo -e "${BLUE}Your master configuration is now active.${NC}"