#!/usr/bin/env bash
set -euo pipefail

# Script to create API key secrets templates from Bitwarden
# Searches for items with *_API_KEY in title and API keys in password/custom fields

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SECRETS_FILE="$SCRIPT_DIR/secrets/ssh-secrets.yaml"
SESSION_FILE="${HOME}/.bw_session"

log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1"
}

# Check if yq is available
if ! command -v yq >/dev/null 2>&1; then
    log "yq not found. Installing..."
    if command -v snap >/dev/null 2>&1; then
        sudo snap install yq
    elif command -v apt >/dev/null 2>&1; then
        sudo apt update && sudo apt install -y yq
    else
        log "Please install yq manually"
        exit 1
    fi
fi

# Unlock Bitwarden if needed
if [[ ! -f "$SESSION_FILE" ]] || ! bw status --session "$(cat "$SESSION_FILE" 2>/dev/null)" >/dev/null 2>&1; then
    log "Bitwarden vault is locked. Attempting to unlock..."

    if [[ -n "${BW_PASSWORD:-}" ]]; then
        BW_SESSION=$(bw unlock --raw "$BW_PASSWORD" 2>/dev/null)
        echo "$BW_SESSION" > "$SESSION_FILE"
        chmod 600 "$SESSION_FILE"
    else
        echo "Please enter your Bitwarden master password:"
        BW_SESSION=$(bw unlock --raw)
        echo "$BW_SESSION" > "$SESSION_FILE"
        chmod 600 "$SESSION_FILE"
    fi
else
    BW_SESSION=$(cat "$SESSION_FILE")
fi

export BW_SESSION

log "Searching for API key secrets in Bitwarden..."

# Create secrets directory if it doesn't exist
mkdir -p "$SCRIPT_DIR/secrets"

# Initialize or backup existing secrets file
if [[ -f "$SECRETS_FILE" ]]; then
    cp "$SECRETS_FILE" "${SECRETS_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
    log "Backed up existing secrets file"
fi

# Get all items and process them
items=$(bw list items --session "$BW_SESSION" 2>/dev/null)

# Arrays to store found API keys
declare -a api_keys_found=()
declare -a field_api_keys_found=()

log "Processing items with *_API_KEY in title..."

# Process items with *_API_KEY in title
echo "$items" | jq -c '.[]' | while read -r item; do
    name=$(echo "$item" | jq -r '.name')
    id=$(echo "$item" | jq -r '.id')

    # Check if name matches *_API_KEY pattern
    if [[ "$name" =~ _API_KEY$ ]]; then
        log "Found API key item: $name"

        # Get password field
        password=$(echo "$item" | jq -r '.login.password // empty')
        if [[ -n "$password" ]] && [[ "$password" != "null" ]]; then
            # Create environment variable name from item name
            env_var=$(echo "$name" | sed 's/_API_KEY$//' | tr '[:lower:]' '[:upper:]' | sed 's/[^A-Z0-9_]/_/g')_API_KEY

            api_keys_found+=("$name:$id:$env_var:$password")
            log "  Password field: $env_var = ${password:0:10}..."
        fi
    fi
done

log "Processing custom fields for API keys..."

# Process custom fields for API keys
echo "$items" | jq -c '.[]' | while read -r item; do
    name=$(echo "$item" | jq -r '.name')
    id=$(echo "$item" | jq -r '.id')

    # Check custom fields
    echo "$item" | jq -c '.fields[]?' 2>/dev/null | while read -r field; do
        field_name=$(echo "$field" | jq -r '.name')
        field_value=$(echo "$field" | jq -r '.value')

        if [[ -n "$field_value" ]] && [[ "$field_value" != "null" ]]; then
            # Check if field name indicates API key
            if [[ "$field_name" =~ (?i)api.?key ]]; then
                # Create environment variable name
                env_var=$(echo "$name" | tr '[:lower:]' '[:upper:]' | sed 's/[^A-Z0-9_]/_/g' | sed 's/__*/_/g' | sed 's/^_\|_$//g')_API_KEY

                field_api_keys_found+=("$name:$id:$field_name:$env_var:$field_value")
                log "Found API key in field '$field_name' of item '$name': $env_var = ${field_value:0:10}..."
            fi
        fi
    done
done

log "Creating/updating secrets templates..."

# Create API keys template if not exists
api_keys_template="$SCRIPT_DIR/secrets/api-keys.tmpl"
if [[ ! -f "$api_keys_template" ]]; then
    cat > "$api_keys_template" << 'EOF'
# API Keys from Bitwarden - Generated by create-api-key-secrets.sh
# Items with *_API_KEY in title and API keys in custom fields
{{ range $key := .api_keys }}
# {{ $key.name }} ({{ $key.source }})
export {{ $key.env_var }}="{{ $key.value }}"
{{ end }}
EOF
    log "Created api-keys.tmpl"
fi

# Update the secrets YAML file
log "Updating secrets/ssh-secrets.yaml..."

# Ensure the file has basic structure
if [[ ! -f "$SECRETS_FILE" ]]; then
    cat > "$SECRETS_FILE" << 'EOF'
# SSH and API Keys Data for Chezmoi Templates
# Generated by create-api-key-secrets.sh

# SSH Configuration
personal_server: "your-server.com"
personal_user: "yourusername"
work_server: "work-server.company.com"
work_user: "workuser"

# SSH Keys
ssh_key_ed25519_github: ""
ssh_key_ed25519_github_name: "GitHub Ed25519 Key"
ssh_key_ed25519_gitlab: ""
ssh_key_ed25519_gitlab_name: "GitLab Ed25519 Key"
ssh_key_rsa_personal: ""
ssh_key_rsa_personal_name: "Personal RSA Key"

# API Keys from Bitwarden
api_keys: []
EOF
fi

# Add found API keys to the YAML
for key_data in "${api_keys_found[@]}"; do
    IFS=':' read -r name id env_var value <<< "$key_data"

    # Check if this key already exists
    if ! yq ".api_keys[] | select(.env_var == \"$env_var\")" "$SECRETS_FILE" >/dev/null 2>&1; then
        yq -i ".api_keys += [{\"name\": \"$name\", \"id\": \"$id\", \"env_var\": \"$env_var\", \"value\": \"$value\", \"source\": \"password\"}]" "$SECRETS_FILE"
        log "Added API key: $env_var"
    else
        log "Updated existing API key: $env_var"
        yq -i "(.api_keys[] | select(.env_var == \"$env_var\")) |= . + {\"value\": \"$value\", \"source\": \"password\"}" "$SECRETS_FILE"
    fi
done

# Add field-based API keys
for key_data in "${field_api_keys_found[@]}"; do
    IFS=':' read -r name id field_name env_var value <<< "$key_data"

    # Check if this key already exists
    if ! yq ".api_keys[] | select(.env_var == \"$env_var\")" "$SECRETS_FILE" >/dev/null 2>&1; then
        yq -i ".api_keys += [{\"name\": \"$name\", \"id\": \"$id\", \"field\": \"$field_name\", \"env_var\": \"$env_var\", \"value\": \"$value\", \"source\": \"field\"}]" "$SECRETS_FILE"
        log "Added field API key: $env_var (from field '$field_name')"
    else
        log "Updated existing field API key: $env_var"
        yq -i "(.api_keys[] | select(.env_var == \"$env_var\")) |= . + {\"value\": \"$value\", \"field\": \"$field_name\", \"source\": \"field\"}" "$SECRETS_FILE"
    fi
done

log "API key secrets creation completed!"
echo
echo "=== SUMMARY ==="
echo "API keys from *_API_KEY titles: ${#api_keys_found[@]}"
echo "API keys from custom fields: ${#field_api_keys_found[@]}"
echo "Total API keys processed: $(( ${#api_keys_found[@]} + ${#field_api_keys_found[@]} ))"
echo
echo "Files created/updated:"
echo "- secrets/api-keys.tmpl (template)"
echo "- secrets/ssh-secrets.yaml (data)"
echo
echo "To apply the secrets to your system:"
echo "  chezmoi apply"
echo
echo "The API keys will be available as environment variables after applying."